### ISSUE TITLE
module name should be simple name rather than package name.

### ISSUE THREAD

**Issue by torutk** [yas99en/moreemacsnb#1]
After install this nice plugin, it shows like "io.github.yas99en.moreemacsnb.core" on the Plugins window.
([Tools] > [Plugins] > [Installed]tab)

Other plugins are shows like "Git", "JUnit", ...

It can be changed by modifying OpenIDE-Module-Name in Bundle.properties file.

``` diff
- OpenIDE-Module-Name=io.github.yas99en.moreemacsnb.core
+ OpenIDE-Module-Name=MoreEmacs
```

``` diff
- OpenIDE-Module-Name=io.github.yas99en.moreemacsnb.icu
+ OpenIDE-Module-Name=ICU4J
```

**Comment by yas99en** [comment]
I fixed the module name to 'MoreEmacs'.
